### ISSUE TITLE
Graceful shutdowns

### ISSUE THREAD

**Issue by prologic** [prologic/eris#30]
Right now a `SIGINT` or `SIGTERM` just kills the server. There is no graceful shutdown even though internally the server is designed to blast out a global notice to all users with the text "Shutting down ..."

* Add signal handlers for `SIGINT` and `SIGTERM`
* Invoke the `server.Shutdown()` method.
* Wait for all clients to disconnect.

**Comment by DanielOaks** [comment]
fwiw, it's good to ensure that a `\r\n` gets sent after `"Shutting down..."` (so that clients correctly process the shutting down message). I've had it where I've sent out the final notice/message, but clients won't parse it because there's no `\r\n` after it.
