### ISSUE TITLE
idea for channel visibility and modes 

### ISSUE THREAD

**Issue by bear** [prologic/eris#35]
in traditional IRCd you can have hidden channels and registered users, for Eris I would like to suggest more layers:

* `#public` -- visible to anyone, think of the lobby
* `#hidden` -- visible to anyone who is connected securely and registered
* `#secret` -- visible only to those who are members and you have to be registered and securely connected to join

Of course NetOps would see all channels and members

**Comment by prologic** [comment]
I would call these:

* Public -- no special modes, visible to anyone.
* Private +p (Private) -- visible only to users connected securely (+z) and registered (+r)
* Secret +s (Secret) -- visible only to users that are members of the channel

Implementing +p properly will however require some further work on SASL auth.
